# Completare la variabile MUMPS PAHT con il percorso di mumps (CON I)
# #da completare per utente
MUMPS_I = -I/u/geo2/sw/Toolchains/gcc+system/4.8/Packages/libs/mumps-mpi/4.10/include
MUMPS_L = -L/u/geo2/sw/Toolchains/gcc+system/4.8/Packages/libs/mumps-mpi/4.10/lib -L/u/geo2/sw/Toolchains/gcc+system/4.8/Packages/libs/scotch-mpi/5.1/lib
MUMPS_l =  -ldmumps -lptscotcherr